// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App-CSharpApi/
// User:        2sichost
// When:        2024-02-29 20:06:02Z
namespace AppCode.Data
{
  // This is a generated class for AppSettings
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppSettings data. <br/>
  /// Generated 2024-02-29 20:06:02Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class AppSettings: AppSettingsAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for AppSettings.
  /// </summary>
  public abstract class AppSettingsAutoGenerated: Custom.Data.CustomItem
  {  }
}