// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Dll.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Dll
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.04.01
// App/Edition: App-CSharpApi/
// User:        2sichost
// When:        2024-03-11 18:33:04Z
namespace AppCode.Data
{
  // This is a generated class for Dll 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Dll data. <br/>
  /// Generated 2024-03-11 18:33:04Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Dll: AutoGenerated.ZagDll
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Dll in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagDll: Custom.Data.CustomItem
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// IgnoreAll as bool. <br/>
    /// To get nullable use .Get("IgnoreAll") as bool?;
    /// </summary>
    public bool IgnoreAll => _item.Bool("IgnoreAll");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");
  }
}