// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Dll.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Dll
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App-CSharpApi/
// User:        2sichost
// When:        2024-02-24 10:50:47Z
namespace AppCode.Data
{
  // This is a generated class for Dll
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Dll data. <br/>
  /// Generated 2024-02-24 10:50:47Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Dll: DllAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for Dll.
  /// </summary>
  public abstract class DllAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _myItem.String("Description", fallback: "");

    /// <summary>
    /// IgnoreAll as bool. <br/>
    /// To get nullable use .Get("IgnoreAll") as bool?;
    /// </summary>
    public bool IgnoreAll => _myItem.Bool("IgnoreAll");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _myItem.String("Name", fallback: "");
  }
}