// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Dll.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Dll
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App-CSharpApi/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for Dll 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Dll data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Dll: AutoGenerated.ZAutoGenDll
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'Dll' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenDll: Custom.Data.CustomItem
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// Group as single item of DllGroup.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type DllGroup was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public DllGroup Group => _group ??= _item.Child<DllGroup>("Group");
    private DllGroup _group;

    /// <summary>
    /// IgnoreAll as bool. <br/>
    /// To get nullable use .Get("IgnoreAll") as bool?;
    /// </summary>
    public bool IgnoreAll => _item.Bool("IgnoreAll");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");
  }
}