// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RuleNamespace.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RuleNamespace
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App-CSharpApi/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for RuleNamespace 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RuleNamespace data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.IgnoreAll`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RuleNamespace: AutoGenerated.ZAutoGenRuleNamespace
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RuleNamespace' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRuleNamespace: Custom.Data.CustomItem
  {
    /// <summary>
    /// IgnoreAll as bool. <br/>
    /// To get nullable use .Get("IgnoreAll") as bool?;
    /// </summary>
    public bool IgnoreAll => _item.Bool("IgnoreAll");

    /// <summary>
    /// IgnoreTypeMembers as bool. <br/>
    /// To get nullable use .Get("IgnoreTypeMembers") as bool?;
    /// </summary>
    public bool IgnoreTypeMembers => _item.Bool("IgnoreTypeMembers");

    /// <summary>
    /// Notes as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Notes", scrubHtml: true) etc.
    /// </summary>
    public string Notes => _item.String("Notes", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}