// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RuleDll.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RuleDll
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App-CSharpApi/
// User:        2sichost
// When:        2024-02-29 20:06:02Z
namespace AppCode.Data
{
  // This is a generated class for RuleDll
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RuleDll data. <br/>
  /// Generated 2024-02-29 20:06:02Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.IgnoreAll`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RuleDll: RuleDllAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for RuleDll.
  /// </summary>
  public abstract class RuleDllAutoGenerated: Custom.Data.CustomItem
  {
    /// <summary>
    /// IgnoreAll as bool. <br/>
    /// To get nullable use .Get("IgnoreAll") as bool?;
    /// </summary>
    public bool IgnoreAll => _item.Bool("IgnoreAll");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}